input {
  beats {
    port => 5044
  }
}

filter {
  if ![service] {
    mutate {
      add_field => { "service" => "unknown" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{[service]}-%{+YYYY.MM.dd}"
  }
}
